name: Next.js CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
      - staging
      - production
  workflow_dispatch:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm run test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t bruklemma/leyulanding-app:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push bruklemma/leyulanding-app:${{ github.sha }}

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Pull Docker Image
      run: |
        docker bruklemma/leyulanding-app:${{ github.sha }}
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Execute commands via SSH
      run: |
        ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
        docker stop Leyulanding-app-dev
        docker rm Leyulanding-app-dev
        docker run -d --name Leyulanding-app-dev -p 6000:3000 bruklemma/leyulanding-app:${{ github.sha }}
        docker ps
       
